// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPdyZG3iIc1HhNFr4gq19ZSBSnxyEz-hE',
    appId: '1:700164288960:web:04b723949dab90a745d825',
    messagingSenderId: '700164288960',
    projectId: 'fireabasevivek',
    authDomain: 'fireabasevivek.firebaseapp.com',
    storageBucket: 'fireabasevivek.appspot.com',
    measurementId: 'G-PQ5BLBGBTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSSF8UwmG28kRz1KA96rrS90x41c_6Jc',
    appId: '1:700164288960:android:cadbd1a67ca22aac45d825',
    messagingSenderId: '700164288960',
    projectId: 'fireabasevivek',
    storageBucket: 'fireabasevivek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ObZKTWRKYddFmMfM4hYl1y7XukYquTA',
    appId: '1:700164288960:ios:35798efd28b5e84f45d825',
    messagingSenderId: '700164288960',
    projectId: 'fireabasevivek',
    storageBucket: 'fireabasevivek.appspot.com',
    androidClientId: '700164288960-42qrj80o6omcgd0mrsbq5aof5g0f0guf.apps.googleusercontent.com',
    iosClientId: '700164288960-ar6o44ttjr0sgsip3t8o8s930isodort.apps.googleusercontent.com',
    iosBundleId: 'com.vivek.chatsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ObZKTWRKYddFmMfM4hYl1y7XukYquTA',
    appId: '1:700164288960:ios:35798efd28b5e84f45d825',
    messagingSenderId: '700164288960',
    projectId: 'fireabasevivek',
    storageBucket: 'fireabasevivek.appspot.com',
    androidClientId: '700164288960-42qrj80o6omcgd0mrsbq5aof5g0f0guf.apps.googleusercontent.com',
    iosClientId: '700164288960-ar6o44ttjr0sgsip3t8o8s930isodort.apps.googleusercontent.com',
    iosBundleId: 'com.vivek.chatsystem',
  );
}
